[package]
name = "mawu"
authors = ["Xqhare"]
version = "2.0.0"
edition = "2024"

[features]
csv = []
toml = []

[dependencies]
athena = { git = "https://github.com/Xqhare/athena"}
nemesis = { git = "https://github.com/Xqhare/nemesis"}
thoth = { git = "https://github.com/Xqhare/thoth"}
horae = { git = "https://github.com/Xqhare/horae"}

[dev-dependencies]
json = "0.12.4"
pretty_assertions = "1.4.0"
